name: MinecartMania
main: com.afforess.minecartmania.MinecartMania
version: 2.1.2 beta 2
author: jrbudda, mze9412, Afforess
database: true
commands:
  mm:
    description: Base MM command class
    usage: /<command>
  st:
    description: Sets the station value, for any station intersection the players may pass in a minecart
    usage: /<command>
  trucompass:
    description: Returns the true compass direction for the direction that the player is facing
    usage: /<command>
permissions:
    minecartmania.*:
        description: Gives access to all minecart mania functionality
        default: op
        children:
            minecartmania.commands.*: true
            minecartmania.signs.*: true
    minecartmania.signs.*:
        description: Gives access to all minecart mania signs functionality
        default: true
        children:
             minecartmania.signs.create.*: true
             minecartmania.signs.break.*: true
    minecartmania.commands.*:
        description: Gives access to all minecart mania commands
        default: op
        children:
            minecartmania.commands.eject: true
            minecartmania.commands.permeject: true
            minecartmania.commands.clearemptycarts: true
            minecartmania.commands.clearpoweredcarts: true
            minecartmania.commands.clearstoragecarts: true
            minecartmania.commands.clearoccupiedcarts: true
            minecartmania.commands.clearallcarts: true
            minecartmania.commands.clearstalledcarts: true
            minecartmania.commands.clearmovingcarts: true
            minecartmania.commands.redraw: true
            minecartmania.commands.hide: true
            minecartmania.commands.momentum: true
            minecartmania.commands.info: true
            minecartmania.commands.trucompass: true
            minecartmania.commands.st: true
            minecartmania.commands.throttle: true
            minecartmania.commands.reload: true
    minecartmania.commands.eject:
        description: Ejects the given player from a minecart, if they are in one. 
        default: op
    minecartmania.commands.permeject:
        description: Ejects the given player from a minecart, and prevents them from re-entering any minecart. This resets if the command is used again for the given player, or if the server is restarted. 
        default: op
    minecartmania.commands.clearemptycarts:
        description: Removes all empty minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearpoweredcarts:
        description: Removes all powered minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearstoragecarts:
        description: Removes all storage minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearoccupiedcarts:
        description: Removes all occupied minecarts from the server, dropping players where they stand. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearallcarts:
        description: Removes all minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearstalledcarts:
        description: Removes any unmoving minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.clearmovingcarts:
        description: Removes any moving minecarts from the server. If -d (destroy) is set, they will not be returned to their owners. If the range is set, only carts inside the range will be cleared. 
        default: op
    minecartmania.commands.redraw:
        description: Sends updates to all connected players to force all clients to redraw minecarts. Causes ~1 second of lag. 
        default: op
    minecartmania.commands.redraw:
        description: Sends updates to all connected players to force all clients to redraw minecarts. Causes ~1 second of lag. 
        default: op
    minecartmania.commands.hide:
        description: Hides all minecarts from view. They will continue moving, but will drop any passengers, and can not be seen unless someone re-logins or /mm redraw is used. 
        default: op
    minecartmania.commands.setconfigkey:
        description: Sets the given configuration key to the given value. The key name and value are case-sensitive. 
        default: op
    minecartmania.commands.help:
        description: Sends updates to all connected players to force all clients to redraw minecarts. Causes ~1 second of lag. 
        default: true
    minecartmania.commands.momentum:
        description: shows the momentum of the minecart the player is in. 
        default: true
    minecartmania.commands.info:
        description: Shows a list of detailed minecart information for the server 
        default: true
    minecartmania.commands.getconfigkey:
        description: shows the value of the given configuration key. The Key is case-sensitive. 
        default: true
    minecartmania.commands.listconfigkeys:
        description: Lists all of the config keys, in a page by page format 
        default: true
    minecartmania.commands.trucompass:
        description: Shows the true (Notch) direction that the player is facing. 
        default: true
    minecartmania.commands.st:
        description: Sets the station value for the player. It must be followed by any string, with numbers and letters. The -s flag saves the value so that it is not reset after 1 station. 
        default: true
    minecartmania.commands.throttle:
        description: Autocart Only. Changes the momentum of the minecart. 100% is normal max speed. Can not exceed 500%. 
        default: true
    minecartmania.signs.create.*:
        description: Gives access to all minecart mania create signs functionality
        default: true
        children:
           minecartmania.signs.create.launchplayersign: true
           minecartmania.signs.create.launchersign: true
           minecartmania.signs.create.setstationsign: true
           minecartmania.signs.create.stopatdestinationsign: true
           minecartmania.signs.create.lockcart: true
           minecartmania.signs.create.unlockcart: true
           minecartmania.signs.create.autoseedsign: true
           minecartmania.signs.create.autotillsign: true
           minecartmania.signs.create.autoharvestsign: true
           minecartmania.signs.create.autotimbersign: true
           minecartmania.signs.create.autoforestsign: true
           minecartmania.signs.create.autosugarsign: true
           minecartmania.signs.create.autoplantsign: true
           minecartmania.signs.create.autocactussign: true
           minecartmania.signs.create.autorecactussign: true
           minecartmania.signs.create.seedoffsign: true
           minecartmania.signs.create.tilloffsign: true
           minecartmania.signs.create.harvestoffsign: true
           minecartmania.signs.create.timberoffsign: true
           minecartmania.signs.create.forestoffsign: true
           minecartmania.signs.create.sugaroffsign: true
           minecartmania.signs.create.plantoffsign: true
           minecartmania.signs.create.cactusoffsign: true
           minecartmania.signs.create.recactusoffsign: true
           minecartmania.signs.create.alterrangesign: true
           minecartmania.signs.create.maxspeedsign: true
           minecartmania.signs.create.ejectsign: true
           minecartmania.signs.create.announcementsign: true
           minecartmania.signs.create.holdingsign: true
           minecartmania.signs.create.elevatorsign: true
           minecartmania.signs.create.ejectatsign: true
           minecartmania.signs.create.farmsign: true
           minecartmania.signs.create.minimumitemsign: true
           minecartmania.signs.create.maximumitemsign: true
           minecartmania.signs.create.jumpsign: true
           minecartmania.signs.create.stationsign: true
           minecartmania.signs.create.killsign: true
           minecartmania.signs.create.platformsign: true
           minecartmania.signs.create.spawnsign: true
           minecartmania.signs.create.setspeedsign: true
           minecartmania.signs.create.magnetsign: true
           minecartmania.signs.create.promptsign: true
           minecartmania.signs.create.catchsign: true
           minecartmania.signs.create.compressitemssign: true
           minecartmania.signs.create.collectitemssign: true
           minecartmania.signs.create.deposititemssign: true
           minecartmania.signs.create.trashitemssign: true
           minecartmania.signs.create.smeltitemssign: true
    minecartmania.signs.create.launchplayersign:
        description: Launch Player
        default: true
    minecartmania.signs.create.launchersign:
        description: Launcher 
        default: true
    minecartmania.signs.create.setstationsign:
        description: Set Station
        default: true
    minecartmania.signs.create.stopatdestinationsign:
        description: Stop At Destination
        default: true
    minecartmania.signs.create.lockcart:
        description: Lock Cart
        default: true
    minecartmania.signs.create.unlockcart:
        description: Unlock Cart
        default: true
    minecartmania.signs.create.autoseedsign:
        description: AutoSeed Sign
        default: true
    minecartmania.signs.create.autotillsign:
        description: AutoTill Sign
        default: true
    minecartmania.signs.create.autoharvestsign:
        description: AutoHarvest Sign
        default: true
    minecartmania.signs.create.autotimbersign:
        description: AutoTimber Sign
        default: true
    minecartmania.signs.create.autoforestsign:
        description: AutoForest Sign
        default: true
    minecartmania.signs.create.autosugarsign:
        description: AutoSugar Sign
        default: true
    minecartmania.signs.create.autoplantsign:
        description: AutoPlant Sign
        default: true
    minecartmania.signs.create.autocactussign:
        description: AutoCactus Sign
        default: true
    minecartmania.signs.create.autorecactussign:
        description: AutoReCactus Sign
        default: true
    minecartmania.signs.create.seedoffsign:
        description: Seed Off Sign
        default: true
    minecartmania.signs.create.tilloffsign:
        description: Till Off Sign
        default: true
    minecartmania.signs.create.harvestoffsign:
        description: Harvest Off Sign
        default: true
    minecartmania.signs.create.timberoffsign:
        description: Timber Off Sign
        default: true
    minecartmania.signs.create.forestoffsign:
        description: Forest Off Sign
        default: true
    minecartmania.signs.create.sugaroffsign:
        description: Sugar Off Sign
        default: true
    minecartmania.signs.create.plantoffsign:
        description: Plant Off Sign
        default: true
    minecartmania.signs.create.cactusoffsign:
        description: Cactus Off Sign
        default: true
    minecartmania.signs.create.recactusoffsign:
        description: ReCactus Off Sign
        default: true
    minecartmania.signs.create.alterrangesign:
        description: Alter Range
        default: true
    minecartmania.signs.create.maxspeedsign:
        description: Max Speed
        default: true
    minecartmania.signs.create.ejectsign:
        description: Eject Sign
        default: true
    minecartmania.signs.create.announcementsign:
        description: Announcement
        default: true
    minecartmania.signs.create.holdingsign:
        description: Holding
        default: true
    minecartmania.signs.create.elevatorsign:
        description: Elevator
        default: true
    minecartmania.signs.create.ejectatsign:
        description: Eject At Location
        default: true
    minecartmania.signs.create.farmsign:
        description: Farm
        default: true
    minecartmania.signs.create.minimumitemsign:
        description: Minimum Item
        default: true
    minecartmania.signs.create.maximumitemsign:
        description: Maximum Item
        default: true
    minecartmania.signs.create.jumpsign:
        description: Jump
        default: true
    minecartmania.signs.create.stationsign:
        description: Station
        default: true
    minecartmania.signs.create.killsign:
        description: Kill
        default: true
    minecartmania.signs.create.platformsign:
        description: Platform
        default: true
    minecartmania.signs.create.spawnsign:
        description: Spawn
        default: true
    minecartmania.signs.create.setspeedsign:
        description: Set Speed 0.0
        default: true
    minecartmania.signs.create.magnetsign:
        description: Magnet
        default: true
    minecartmania.signs.create.promptsign:
        description: Prompt
        default: true
    minecartmania.signs.create.catchsign:
        description: Catch
        default: true
    minecartmania.signs.create.compressitemssign:
        description: Compress Items
        default: true
    minecartmania.signs.create.collectitemssign:
        description: Collect Items
        default: true
    minecartmania.signs.create.deposititemssign:
        description: Deposit Items
        default: true
    minecartmania.signs.create.trashitemssign:
        description: Trash Items
        default: true
    minecartmania.signs.create.smeltitemssign:
        description: Smelt Items
        default: true